config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @room = Room.find(params[:room_id])
    if @room.user_ids.include?(current_user.id)
      @message = Message.new
      @messages = @room.messages.includes(:user)
    else
      redirect_to root_path
    end
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      ActionCable.server.broadcast 'message_channel', {name: current_user.name, content: @message, date: l(@message.created_at)}
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
  
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ress@3.0.0/dist/ress.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="header-title">
    <p><%= @room.name %></p>
    <p>メンバー：
      <% @room.user_ids.each do |user| %>
        <%= User.find(user).name %>
      <% end %>
    </p>
  </div>
  <div class="header-button">
    <%= link_to "チャットルームを削除", room_path(@room), method: :delete %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  </div>
</div>
<div id="messages" data-current-user="<%= current_user.id %>">
  <% @messages.each do |message| %>
    <% if message.user.id == current_user.id %>
      <div class="my-message">
    <% else %>
      <div class="message">
    <% end %>
        <div class="upper-message">
          <div class="message-user">
            <%= message.user.name %>
          </div>
          <div class="message-date">
            <%= l message.created_at %>
          </div>
        </div>
        <div class="lower-message">
          <div class="message-content">
            <p><%= message.content %></p>
          </div>
        </div>
      </div>
  <% end %>
</div>
<%= form_with model: [@room, @message], class: "form-message" do |f| %>
  <%= f.text_field :content, class: "form-content", placeholder: "type a message", autocomplete: "off" %>
  <%= f.submit "送信", class: "form-submit" %>
<% end %>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="user-name">
    <%= link_to current_user.name, root_path %>
  </div>
  <div class="create-room">
    <%= link_to "チャット作成", new_room_path %>
  </div>
</div>
<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
  <div class="main-room">
    <%= link_to "新規チャットルームを作成する", new_room_path %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="chat-room-form">
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="chat-room-form-group">
      <%= f.label :チャットルーム名 %>
      <%= f.text_field :name, placeholder: "チャットルーム名を入力してください" %>
    </div>
    <div class="chat-room-form-group">
      <label for="chat_room_チャットメンバー">チャットメンバー</label>
      <select name="room[user_ids][]">
        <option value="">チャットするユーザーを選択してください</option>
        <% User.where.not(id: current_user.id).each do |user| %>
          <option value="<%= user.id %>"><%= user.name %></option>
        <% end %>
      </select>
      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
    </div>
    <%= f.submit class: "chat-room-create-btn" %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>